version: '3'
services:
  behavior_web:
    build: .
    container_name: behavior_web
    volumes:
      - .:/www
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Bangkok"
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8080 --workers 5 --reload"
    #command: bash -c "gunicorn main:app --workers 5 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:10802 --reload"